ALTER TABLE mihomo
ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE USING updated_at AT TIME ZONE 'UTC';

ALTER TABLE scores_achievement
ALTER COLUMN timestamp TYPE TIMESTAMP WITH TIME ZONE USING timestamp AT TIME ZONE 'UTC';

ALTER TABLE sessions
ALTER COLUMN expiry TYPE TIMESTAMP WITH TIME ZONE USING expiry AT TIME ZONE 'UTC';

ALTER TABLE warps
ALTER COLUMN timestamp TYPE TIMESTAMP WITH TIME ZONE USING timestamp AT TIME ZONE 'UTC';
