ALTER TABLE warps_stats_4
ADD COLUMN median INT4 NOT NULL DEFAULT 0;

ALTER TABLE warps_stats_4
ADD COLUMN rank_median INT4 NOT NULL DEFAULT 0;

ALTER TABLE warps_stats_5
ADD COLUMN median INT4 NOT NULL DEFAULT 0;

ALTER TABLE warps_stats_5
ADD COLUMN rank_median INT4 NOT NULL DEFAULT 0;
