CREATE TABLE IF NOT EXISTS gacha_banners
(
    id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Game id, 1 = HSR, 2 = ZZZ, 3 = Genshin, etc.
    game_id            integer NOT NULL,

    -- Banner gacha type, depends on the game (1 = hsr standard, 11 = hsr lightcone, 1001 = zzz standard, etc.)
    gacha_type         integer,
    -- Banner id, optional, unique id of banner used by the game (only HSR and ZZZ have these?)
    banner_id          integer,

    title              text,
    internal_name      text,
    version            text,

    rate_up_5_stars    int[] DEFAULT '{}' NOT NULL,
    rate_up_4_stars    int[] DEFAULT '{}' NOT NULL,

    start_time         timestamp without time zone NOT NULL,
    end_time           timestamp without time zone NOT NULL,
    timezone_dependant boolean NOT NULL DEFAULT FALSE,

    disabled           boolean NOT NULL DEFAULT FALSE,
    created_at         timestamp WITH TIME ZONE DEFAULT timezone('UTC'::text, now()) NOT NULL
);
