//pub mod books_percent;
pub mod achievements_percent;
pub mod character_averages;
pub mod dimbreath;
pub mod gi_achievements_percent;
pub mod scores;
pub mod star_rail_res;
pub mod zzz_achievements_percent;
//mod community_tier_list;
pub mod signals_stats;
pub mod warps_stats;
pub mod wishes_stats;
