name: Clippy

on:
  push:
  pull_request:

jobs:
  deploy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Get Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Verify gacha changes
        run: scripts/verify-gacha.sh
